name: Backend

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Upload Test Report to Codacy
        run: |
            export CODACY_PROJECT_TOKEN=${{secrets.CODACY_TEST_COVERAGE_API_TOKEN}}
            bash <(curl -Ls https://coverage.codacy.com/get.sh)
