name: Frontend

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
      - name: Install & Lint
        run: |
          npm install -g pnpm
          pnpm install
          pnpm lint
      - name: Testing and coverage
        run: |
          pnpm coverage
      - name: Building
        run: pnpm build
      - name: Upload Test Report to Codacy
        run: |
            export CODACY_PROJECT_TOKEN=${{secrets.CODACY_TEST_COVERAGE_API_TOKEN}}
            bash <(curl -Ls https://coverage.codacy.com/get.sh)
